### PR TITLE
docs: add note about version compatibility

### PR DESCRIPTION
**Pull request by nfriend**
### What does this PR do?

Adds a note about which versions of GitLab are supported by this plugin, and also adds a note about a specific breaking change in GitLab 14.0.

### CODE REVIEW

**Comment by nfriend** [comment]
@keplersj @travi Can you please review this proposed compatibility guideline? 🙏 

For context, some of the users of this plugin are seeing errors due to using an unsupported version of GitLab: https://github.com/semantic-release/gitlab/issues/239.

Let me know if this seems reasonable (and consistent with other `semantic-release` plugins).

**Comment by travi** [comment]
this looks good, although i am a little confused by the link to the issue. it sounds like you are referring to the later comment specifically about the v14 change. there is also a mention of v11 support in that thread and this seems to contradict with entertaining the PR to continue enabling v11 support beyond EOL. i'm supportive of this language and dropping support of gitlab versions that are EOL, but just want to make sure that aligns with what we decide to do with that PR. do we intend to close that PR as part of this?

**Review by travi — APPROVED** [review]
i like this messaging, but lets resolve the question about v11 before merging

**Comment by nfriend** [comment]
> here is also a mention of v11 support in that thread and this seems to contradict with entertaining the PR to continue enabling v11 support beyond EOL.

@travi Sorry, yes, that is a little confusing - I should have explained in more detail. Since https://github.com/semantic-release/gitlab/pull/240 was already in motion, and since it's a forwards-compatible change, I thought we could make an exception (especially since support for v11 _just_ ended) and get this fix merged. But going forward, we wouldn't entertain any v11-specific fixes.

The v14 breaking change is a separate issue, but I thought I'd address it in the same section since they're both related to the version of the GitLab instance.

**Comment by travi** [comment]
> I thought we could make an exception (especially since support for v11 _just_ ended) and get this fix merged. But going forward, we wouldn't entertain any v11-specific fixes.

i think that is fair if that ends up working out. it seems low maintenance if it does merge, but i think it would also be reasonable if it didnt merge. you can make the call on that piece.

whether dropping support for gitlab versions constitutes a breaking change or not is something we should also define sometime. i lean toward yes, but that would mean taking steps at the appropriate times to publish the breaking change. it may make sense to hold off until a change is made that is actually incompatible with an older version, but i wouldnt want to carry the burden of testing against end-of-life versions to know when that happens. thats the balance that makes me hesitate slightly about merging something to support a version that is already (even if only recently) EOL, since it becomes questionable when it is safe to remove vs keeping it around forever for the sake of being uncertain.

all of that is not to convince you to go one way or another, but rather just to share some of the thoughts on my mind around the topic.

**Comment by nfriend** [comment]
@travi Thanks for your thoughts!

> whether dropping support for gitlab versions constitutes a breaking change or not is something we should also define sometime. i lean toward yes, but that would mean taking steps at the appropriate times to publish the breaking change.

I agree, I think a breaking change would make the most sense in that scenario.

>  thats the balance that makes me hesitate slightly about merging something to support a version that is already (even if only recently) EOL, since it becomes questionable when it is safe to remove vs keeping it around forever for the sake of being uncertain.

Thanks for this input! That makes a lot of sense. I'm now leaning toward closing https://github.com/semantic-release/gitlab/pull/240 to avoid the maintenance burden you mentioned above.

---

Is there anything else you'd like to see outlined in this docs update? Or are you okay if I merge this in its current state?

**Comment by travi** [comment]
> Is there anything else you'd like to see outlined in this docs update? Or are you okay if I merge this in its current state?

this seems great for this stage. thanks for putting this together!

**Pull request merged**
