### PR TITLE
feat: templating of `path`

### PR DESCRIPTION
**Pull request by mattyclarkson**
Runs Lodash templating on the asset path.

### CODE REVIEW

**Comment by fgreinacher** [comment]
Thanks @mattyclarkson! The change looks good! Please update the relevant [readme chapter](https://github.com/semantic-release/gitlab#assets) and add [a test case](https://github.com/semantic-release/gitlab/blob/master/test/publish.test.js) that verifies the templating works and we can get this in 🙇

**Comment by mattyclarkson** [comment]
> Thanks @mattyclarkson! The change looks good! Please update the relevant [readme chapter](https://github.com/semantic-release/gitlab#assets) and add [a test case](https://github.com/semantic-release/gitlab/blob/master/test/publish.test.js) that verifies the templating works and we can get this in 🙇

Done ✔️ Hope it is enough test coverage!

**Comment by mattyclarkson** [comment]
Ooo, will fix up the test failures. Classic "worked on my machine" 😆

**Review by fgreinacher — APPROVED** [review]
Thanks!

**Pull request merged**
