### PR TITLE
fix(success-comment): add missing dot and line break to improve readability

### LINKED ISSUE #351: successComment format
Hi,

Is possible to set the sentence `Your ...` on new line every time? And if the sentence `The release is...` have only one intel, finish with a dot?

image

Expected:

```
The release is available on GitLab release.

Your semantic-release bot 📦 🚀
```
Thank you.

### PR DESCRIPTION
**Pull request by JonasSchubert**
As suggested in #351 I added a dot and line break to improve readability.

Fixes #351

### CODE REVIEW

**Comment by borisdamevin** [comment]
@travi :)

**Comment by fgreinacher** [comment]
Thanks for tagging me, I'm catching up after a couple days sickness, will take look later today!

**Comment by fgreinacher** [comment]
> @fgreinacher we really appreciate your help, but please don't interpret a review request as asking you to respond more quickly

Thanks for highlighting this @travi! (I did not interpret it like that, but others might very well do so!)

**Comment by JonasSchubert** [comment]
Thanks for the review! 👍

**Pull request merged**
