### PR TITLE
fix: better error logging for network errors

### PR DESCRIPTION
**Pull request by nfriend**
### What does this PR do?

Adds some additional logging to `publish.js`, including error logs when requests to GitLab's API fail.

### Why?

Currently, if a request to GitLab's API fails, this plugin logs a generic error message without any specifics. This makes it hard for end-users to diagnose and fix issues.

### CODE REVIEW

**Comment by nfriend** [comment]
@keplersj I see you're one of the other maintainers of this plugin 😄 Would you mind reviewing this PR?

**Review by travi — APPROVED** [review]
seems reasonable to me 👍🏼

**Comment by nfriend** [comment]
Proceeding with a self-merge since this has @travi's approval above.

(Please let me know if this isn't the proper process!)

**Comment by travi** [comment]
> (Please let me know if this isn't the proper process!)

you're good to merge as long as nothing is preventing it. i usually wont merge when you have the premission since you have more context on whether you are wanting to wait for anything else before it happens. thanks for your help here :)

**Pull request merged**
